In [1]:
import numpy  as np
import pandas as pd

In [2]:
string_data = pd.Series(['aardvark','artichoke',np.nan,'avpcado'])

In [3]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
string_data[0] = None

In [5]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [6]:
from numpy import nan as NA

In [7]:
data = pd.Series([1,NA,3.5,NA,7])

In [8]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [9]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data = pd.DataFrame([[1.,6.5,3.],[1.,NA,NA],
                    
                    [NA,NA,NA],[NA,6.5,3]])

In [11]:
cleaned = data.dropna()

In [12]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [13]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [14]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [15]:
data[4] = NA

In [16]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [17]:
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [28]:
df = pd.DataFrame(np.random.randn(7,3))

In [29]:
df.iloc[:4,1] = NA

In [30]:
df.iloc[:2,2] = NA

In [31]:
df

0         1         2
0  0.533302       NaN       NaN
1  0.307679       NaN       NaN
2 -0.424341       NaN  0.232845
3 -0.326023       NaN  0.340189
4 -1.111474  1.371443  1.091484
5  0.232373  0.617030  1.805929
6  0.938679 -0.457947 -0.203062

In [32]:
df.dropna()

0         1         2
4 -1.111474  1.371443  1.091484
5  0.232373  0.617030  1.805929
6  0.938679 -0.457947 -0.203062

In [33]:
df.dropna(thresh=2)

0         1         2
2 -0.424341       NaN  0.232845
3 -0.326023       NaN  0.340189
4 -1.111474  1.371443  1.091484
5  0.232373  0.617030  1.805929
6  0.938679 -0.457947 -0.203062

In [34]:
df.fillna(0)

0         1         2
0  0.533302  0.000000  0.000000
1  0.307679  0.000000  0.000000
2 -0.424341  0.000000  0.232845
3 -0.326023  0.000000  0.340189
4 -1.111474  1.371443  1.091484
5  0.232373  0.617030  1.805929
6  0.938679 -0.457947 -0.203062

In [36]:
df.fillna({1:0.5,2:0})

0         1         2
0  0.533302  0.500000  0.000000
1  0.307679  0.500000  0.000000
2 -0.424341  0.500000  0.232845
3 -0.326023  0.500000  0.340189
4 -1.111474  1.371443  1.091484
5  0.232373  0.617030  1.805929
6  0.938679 -0.457947 -0.203062

In [37]:
_ = df.fillna(0,inplace=True)

In [38]:
df

0         1         2
0  0.533302  0.000000  0.000000
1  0.307679  0.000000  0.000000
2 -0.424341  0.000000  0.232845
3 -0.326023  0.000000  0.340189
4 -1.111474  1.371443  1.091484
5  0.232373  0.617030  1.805929
6  0.938679 -0.457947 -0.203062

In [39]:
_

In [40]:
df = pd.DataFrame(np.random.randn(6,3))

In [45]:
df.iloc[2:,1] = NA
df.iloc[4:,2] = NA

In [46]:
df.fillna(method='ffill')

0         1         2
0  0.632969  0.001553  0.650152
1 -1.608570  1.394151  1.598300
2 -1.561858  1.394151  0.380439
3  1.726500  1.394151 -0.080647
4 -2.094430  1.394151 -0.080647
5 -0.418447  1.394151 -0.080647

In [47]:
df.fillna(method='ffill',limit=2)

0         1         2
0  0.632969  0.001553  0.650152
1 -1.608570  1.394151  1.598300
2 -1.561858  1.394151  0.380439
3  1.726500  1.394151 -0.080647
4 -2.094430       NaN -0.080647
5 -0.418447       NaN -0.080647

In [48]:
data = pd.Series([1.,NA,3.5,NA,7])

In [49]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [50]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [52]:
data = pd.DataFrame({'k1':['one','two']*3 + ['two'],
                   'k2':[1,1,2,3,3,4,4]})

In [53]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [54]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [56]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [63]:
data['v1'] = range(7)

In [58]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [59]:
data.drop_duplicates(['k1','k2'],keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [71]:
data = pd.DataFrame({'food':['bacon','polled pork',
                            'bacon','Pastraml','corned beef','Bacon','pastraml','honey ham','novlox'],
                    'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [72]:
data

food  ounces
0        bacon     4.0
1  polled pork     3.0
2        bacon    12.0
3     Pastraml     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastraml     3.0
7    honey ham     5.0
8       novlox     6.0

In [83]:
meat_to_animal={'bacon':'pig','polled pork':'pig','pastraml':'cow','corned beef':'cow','honey ham':'pig','novlox':'salmon'}

In [84]:
lowercased = data['food'].str.lower()

In [85]:
lowercased

0          bacon
1    polled pork
2          bacon
3       pastraml
4    corned beef
5          bacon
6       pastraml
7      honey ham
8         novlox
Name: food, dtype: object

In [86]:
data['animal'] = lowercased.map(meat_to_animal)

In [87]:
data

food  ounces  animal
0        bacon     4.0     pig
1  polled pork     3.0     pig
2        bacon    12.0     pig
3     Pastraml     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastraml     3.0     cow
7    honey ham     5.0     pig
8       novlox     6.0  salmon

In [89]:
data['food'].map(lambda x:meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [90]:
data = pd.Series([1.,-999.,2.,-999.,-1000.,3.])

In [91]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [92]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [93]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [94]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [96]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [97]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),
                   index=['Ohio','Colorado','New York'],
                   columns=['one','two','three','four'])

In [98]:
transform = lambda x: x[:4].upper()

In [99]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [100]:
data.index = data.index.map(transform)

In [101]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [102]:
data.rename(index = str.title,columns = str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [103]:
data.rename(index = {'OHIO':'INDATA'},columns={'three':'peekaboo'})

one  two  peekaboo  four
INDATA    0    1         2     3
COLO      4    5         6     7
NEW       8    9        10    11

In [104]:
ages = [20,22,13,65,87,12,87,58,12,55,36,38,81]

In [105]:
bins = [18,25,35,60,100]

In [106]:
cats = pd.cut(ages,bins)

In [107]:
cats

[(18.0, 25.0], (18.0, 25.0], NaN, (60.0, 100.0], (60.0, 100.0], ..., NaN, (35.0, 60.0], (35.0, 60.0], (35.0, 60.0], (60.0, 100.0]]
Length: 13
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [108]:
cats.codes

array([ 0,  0, -1,  3,  3, -1,  3,  2, -1,  2,  2,  2,  3], dtype=int8)

In [109]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [110]:
pd.value_counts(cats)

(60, 100]    4
(35, 60]     4
(18, 25]     2
(25, 35]     0
dtype: int64

In [111]:
group_names = ['youth','youngAdult','middleAged','Senior']

In [113]:
pd.cut(ages,bins,labels=group_names)

[youth, youth, NaN, Senior, Senior, ..., NaN, middleAged, middleAged, middleAged, Senior]
Length: 13
Categories (4, object): [youth < youngAdult < middleAged < Senior]

In [114]:
data = np.random.randn(20)

In [115]:
data

array([-1.3235019 , -1.05431894,  0.03919143,  0.78939146,  0.44975099,
       -1.59903634,  1.71345677, -0.65199896,  0.31328098,  0.49027152,
       -0.33434841, -0.61541661, -0.71970334, -0.86586068, -1.10787495,
        2.11549534, -0.10991363, -0.50271875,  0.63044885, -0.04151406])

In [116]:
pd.cut(data,4,precision=2)

[(-1.6, -0.67], (-1.6, -0.67], (-0.67, 0.26], (0.26, 1.19], (0.26, 1.19], ..., (1.19, 2.12], (-0.67, 0.26], (-0.67, 0.26], (0.26, 1.19], (-0.67, 0.26]]
Length: 20
Categories (4, interval[float64]): [(-1.6, -0.67] < (-0.67, 0.26] < (0.26, 1.19] < (1.19, 2.12]]

In [117]:
pd.qcut(data,[0,0.1,0.5,0.9,1])

[(-1.5999999999999999, -1.129], (-1.129, -0.222], (-0.222, 0.882], (-0.222, 0.882], (-0.222, 0.882], ..., (0.882, 2.115], (-0.222, 0.882], (-1.129, -0.222], (-0.222, 0.882], (-0.222, 0.882]]
Length: 20
Categories (4, interval[float64]): [(-1.5999999999999999, -1.129] < (-1.129, -0.222] < (-0.222, 0.882] < (0.882, 2.115]]

In [118]:
data = pd.DataFrame(np.random.randn(1000,4))

In [119]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.045701    -0.014128     0.017996     0.041555
std       1.040716     1.001222     1.031753     0.983440
min      -3.057182    -3.490278    -3.356766    -3.470610
25%      -0.670804    -0.708228    -0.671909    -0.654913
50%       0.013183    -0.010754     0.029520     0.076982
75%       0.765402     0.644749     0.686171     0.746298
max       3.506166     3.860311     3.266169     3.083455

In [120]:
col = data[2]

In [122]:
col[np.abs(col)>3]

526   -3.232404
565    3.266169
569   -3.356766
854    3.245459
Name: 2, dtype: float64

In [123]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
23  -3.057182  1.483907 -0.298720 -0.127373
36   3.506166  0.146438 -0.749007  1.364688
115  0.205593  0.548207 -1.300104  3.032206
125 -0.505343 -3.293761 -0.103921  1.161148
160 -1.691214  3.254055  1.734141  1.343765
203 -1.798307 -3.033348 -0.823733  0.438906
438  0.457409 -3.021711 -0.711624  1.141361
487  0.265734 -3.065632  1.014868  1.280858
494 -0.043855 -0.852341  0.346487 -3.470610
517  3.432787  2.230612 -0.721565  0.867909
526  0.777939  0.753458 -3.232404 -1.154359
565 -1.883265 -1.163378  3.266169 -0.921986
569  0.679896 -1.936454 -3.356766 -0.802505
609 -0.412981  3.860311  0.606497  1.424066
845 -0.764248 -3.490278 -0.303814 -1.711003
851  3.036067  0.296743  0.431098  0.887593
854 -1.503922 -1.655501  3.245459 -0.715490
858  1.584487 -3.137977 -0.702708  0.432857
903 -1.019059 -0.232217 -0.582467 -3.026107
968 -0.671890  1.405734 -0.807204  3.083455

In [124]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [125]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.044784    -0.014199     0.018073     0.041936
std       1.037557     0.994148     1.028391     0.981435
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.670804    -0.708228    -0.671909    -0.654913
50%       0.013183    -0.010754     0.029520     0.076982
75%       0.765402     0.644749     0.686171     0.746298
max       3.000000     3.000000     3.000000     3.000000

In [126]:
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0  1.0 -1.0
1  1.0  1.0  1.0 -1.0
2  1.0  1.0 -1.0  1.0
3  1.0 -1.0  1.0 -1.0
4 -1.0  1.0  1.0  1.0

In [127]:
df = pd.DataFrame(np.arange(5*4).reshape(5,4))

In [129]:
sampler = np.random.permutation(5)

In [130]:
sampler

array([2, 1, 3, 4, 0])

In [131]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [132]:
df.take(sampler)

0   1   2   3
2   8   9  10  11
1   4   5   6   7
3  12  13  14  15
4  16  17  18  19
0   0   1   2   3

In [133]:
df.sample(3)

0   1   2   3
2   8   9  10  11
0   0   1   2   3
3  12  13  14  15

In [135]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'],
                  'datal':range(6)})

In [136]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [137]:
mnames = ['movie_id','titlt','genres']

In [140]:
movies = pd.read_table('movies.dat',sep='::',header = None,names = mnames)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [141]:
movies[:10]

movie_id                               titlt                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [142]:
all_genres = []

In [143]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [144]:
genres = pd.unique(all_genres)

In [145]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [147]:
zero_matrix = np.zeros((len(movies),len(genres)))

In [148]:
dummies = pd.DataFrame(zero_matrix,columns=genres)

In [149]:
gen = movies.genres[0]

In [150]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [151]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [152]:
for i,gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i,indices] = 1

In [153]:
 movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [154]:
movies_windic.iloc[0]

movie_id                                       1
titlt                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       