In [1]:
import pandas as pd

In [2]:
from pandas import Series,DataFrame

In [3]:
obj = pd.Series([4,7,-5,-3])

In [4]:
obj

0    4
1    7
2   -5
3   -3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5, -3], dtype=int64)

In [8]:
obj.index   #like range(4)

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2 = pd.Series([4,7,-5,-3], index=['d','b','c','a'])

In [10]:
obj2

d    4
b    7
c   -5
a   -3
dtype: int64

In [11]:
obj2.index

Index(['d', 'b', 'c', 'a'], dtype='object')

In [13]:
obj2['a']

-3

In [14]:
obj2['a'] = -1 

In [15]:
obj2

d    4
b    7
c   -5
a   -1
dtype: int64

In [16]:
obj2.sort_index

<bound method Series.sort_index of d    4
b    7
c   -5
a   -1
dtype: int64>

In [17]:
obj2.sort_values

<bound method Series.sort_values of d    4
b    7
c   -5
a   -1
dtype: int64>

In [18]:
obj2[obj2 > 0]

d    4
b    7
dtype: int64

In [19]:
obj2 *2

d     8
b    14
c   -10
a    -2
dtype: int64

In [21]:
import numpy as np

In [22]:
np.exp(obj2)

d      54.598150
b    1096.633158
c       0.006738
a       0.367879
dtype: float64

In [23]:
np.exp(1)

2.718281828459045

In [24]:
np.exp(2)

7.38905609893065

In [25]:
2.718281828459045 * 2.718281828459045

7.3890560989306495

In [26]:
2.718281828459045 ** 8

2980.957987041727

In [27]:
'a' in obj2

True

In [28]:
sdata = {'obil':24000,'oji':45000,'qwe':10000,'qow':5000}

In [29]:
obj3 = pd.Series(sdata)

In [30]:
obj3

obil    24000
oji     45000
qwe     10000
qow      5000
dtype: int64

In [31]:
sdata

{'obil': 24000, 'oji': 45000, 'qwe': 10000, 'qow': 5000}

In [32]:
tdata = {1:5,2:5,3:5,4:5,5:5}

In [33]:
obt = pd.Series(tdata)

In [34]:
obt

1    5
2    5
3    5
4    5
5    5
dtype: int64

In [35]:
obt.skew()

0

In [36]:
obt.std()

0.0

In [37]:
obt.median()

5.0

In [38]:
obt.quantile(q=0.25)

5.0

In [39]:
obt.kurt()

0

In [41]:
np.histogram(obt.values,bins=np.arange(0,10,1))

(array([0, 0, 0, 0, 0, 5, 0, 0, 0], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [42]:
states = ['obil','oji','qwe','japan']

In [43]:
obj4 = pd.Series(sdata,index=states)

In [44]:
obj4

obil     24000.0
oji      45000.0
qwe      10000.0
japan        NaN
dtype: float64

In [45]:
pd.isnull(obj4)

obil     False
oji      False
qwe      False
japan     True
dtype: bool

In [46]:
pd.notnull(obj4)

obil      True
oji       True
qwe       True
japan    False
dtype: bool

In [47]:
obj4.isnull()

obil     False
oji      False
qwe      False
japan     True
dtype: bool

In [48]:
obj3

obil    24000
oji     45000
qwe     10000
qow      5000
dtype: int64

In [49]:
obj4

obil     24000.0
oji      45000.0
qwe      10000.0
japan        NaN
dtype: float64

In [50]:
obj3+obj4

japan        NaN
obil     48000.0
oji      90000.0
qow          NaN
qwe      20000.0
dtype: float64

In [51]:
obj4.name = 'population'

In [52]:
obj.index.name = 'states'

In [53]:
obj4.index.name = 'states'

In [54]:
obj4

states
obil     24000.0
oji      45000.0
qwe      10000.0
japan        NaN
Name: population, dtype: float64

In [55]:
obj

states
0    4
1    7
2   -5
3   -3
dtype: int64

In [56]:
obj.index = ['bob','anna','steve','jeff']

In [57]:
obj

bob      4
anna     7
steve   -5
jeff    -3
dtype: int64

In [86]:
data = {'states':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
       'year':[2000,2001,2002,2001,2002,2003],
       'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}

In [87]:
frame = pd.DataFrame(data)

In [88]:
frame

states  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [89]:
frame.head()

states  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [90]:
pd.DataFrame(data,columns=['year','states','pop'])

year  states  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [91]:
frame2 = pd.DataFrame(data,columns = ['year','states','pop','debt'],index = ['one','two','three','four','five','six'])

In [92]:
frame2

year  states  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [93]:
frame2.columns

Index(['year', 'states', 'pop', 'debt'], dtype='object')

In [94]:
frame2['states']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: states, dtype: object

In [95]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [96]:
frame2.loc['three']

year      2002
states    Ohio
pop        3.6
debt       NaN
Name: three, dtype: object

In [97]:
frame2.iloc[3]

year        2001
states    Nevada
pop          2.4
debt         NaN
Name: four, dtype: object

In [98]:
frame2['debt'] = 16.5

In [99]:
frame2

year  states  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [100]:
frame2['debt'] = np.arange(6.0)

In [101]:
frame2

year  states  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [102]:
val = pd.Series([-1.2,-1.5,-1.7],index = ['two','four','five'])

In [103]:
frame2['debt'] = val

In [104]:
frame2

year  states  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [105]:
frame2['eastern'] = frame2.states == 'Ohio'

In [106]:
frame2

year  states  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [107]:
del frame2['eastern']

In [108]:
frame2

year  states  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [109]:
pop = {'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [110]:
frame3 = pd.DataFrame(pop)

In [111]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [112]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [114]:
pd.DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [115]:
pdata = {'Ohio':frame3['Ohio'][:-1],
        'Nevada':frame3['Nevada'][:2]}

In [116]:
pdata

{'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64, 'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64}

In [117]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [118]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [120]:
frame3.index.name = 'year';frame3.columns.name = 'states'

In [121]:
frame3

states  Nevada  Ohio
year                
2000       NaN   1.5
2001       2.4   1.7
2002       2.9   3.6

In [122]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [123]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [124]:
obj = pd.Series(range(3),index = ['a','b','c'])

In [125]:
index = obj.index

In [126]:
index

Index(['a', 'b', 'c'], dtype='object')

In [127]:
index[1:]

Index(['b', 'c'], dtype='object')

In [129]:
index[0] = 'q'

TypeError: Index does not support mutable operations

In [131]:
labels = pd.Index(np.arange(3))

In [132]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [133]:
obj2 = pd.Series([1.5,-2.5,0],index = labels)

In [134]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [135]:
obj2.index is labels

True

In [136]:
frame3

states  Nevada  Ohio
year                
2000       NaN   1.5
2001       2.4   1.7
2002       2.9   3.6

In [137]:
frame3.columnsa

Index(['Nevada', 'Ohio'], dtype='object', name='states')

In [139]:
'Ohio' in frame3.columns

True

In [140]:
2002 in frame3.index

True

In [141]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [143]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [145]:
obj = pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])

In [146]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [148]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [149]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [150]:
obj3 = pd.Series(['blue','purple','yellow'],index = [0,2,4])

In [151]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [153]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [157]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index = ['a','c','d'],
                    columns = ['Ohio','Texas','California'])

In [158]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [160]:
frame2 = frame.reindex (['a','b','c','d','e'])

In [161]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0
e   NaN    NaN         NaN

In [162]:
states = ['Texas','Utah','California']

In [163]:
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [164]:
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])

In [165]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [166]:
new_obj = obj.drop('c')

In [167]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [169]:
obj.drop(['d','e'])

a    0.0
b    1.0
c    2.0
dtype: float64

In [170]:
obj = pd.Series(np.arange(4.0),index = ['a','b','c','d'])

In [171]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [172]:
obj['b']

1.0

In [173]:
obj[1]

1.0

In [174]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [175]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [176]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [177]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [179]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [180]:
obj['b':'c'] = 5

In [181]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [183]:
ser = pd.Series(np.arange(3.))

In [184]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [185]:
ser[:1]

0    0.0
dtype: float64

In [186]:
ser.loc[1:]

1    1.0
2    2.0
dtype: float64

In [188]:
ser.iloc[1:]

1    1.0
2    2.0
dtype: float64

In [189]:
 s1 = pd.Series([7.3,-2.5,3.4,1.5],index = ['a','e','c','d'])

In [190]:
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index = ['a','c','e','f','g'])

In [191]:
s1

a    7.3
e   -2.5
c    3.4
d    1.5
dtype: float64

In [192]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [193]:
s1+s2

a    5.2
c    7.0
d    NaN
e   -4.0
f    NaN
g    NaN
dtype: float64

In [197]:
df1 = pd.DataFrame(np.arange(12.).reshape(3,4),
                  columns = list('abcd'))

In [202]:
df2 = pd.DataFrame(np.arange(20.).reshape(4,5),
                  columns = list('abcde'))

In [203]:
df2.loc[1,'b'] = np.nan

In [204]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [205]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [206]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [208]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [209]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [210]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [211]:
df1.reindex(columns = df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [212]:
arr = np.arange(12.).reshape(3,4)

In [213]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [214]:
arr[0]

array([0., 1., 2., 3.])

In [215]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [221]:
frame = pd.DataFrame(np.random.randn(4,3),
                    columns = list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])

In [222]:
frame

b         d         e
Utah    0.423168  0.974551  0.318243
Ohio   -1.655331 -0.164611 -0.160118
Texas  -0.306191 -0.137038 -1.368707
Oregon -0.531577  1.093280 -0.339105

In [223]:
np.abs(frame)

b         d         e
Utah    0.423168  0.974551  0.318243
Ohio    1.655331  0.164611  0.160118
Texas   0.306191  0.137038  1.368707
Oregon  0.531577  1.093280  0.339105

In [225]:
f = lambda x:x.max() - x.min()

In [226]:
frame.apply(f)

b    2.078499
d    1.257891
e    1.686950
dtype: float64

In [228]:
frame.apply(f,axis='columns')

Utah      0.656308
Ohio      1.495213
Texas     1.231669
Oregon    1.624857
dtype: float64

In [229]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

In [230]:
frame.apply(f)

b         d         e
min -1.655331 -0.164611 -1.368707
max  0.423168  1.093280  0.318243

In [231]:
format = lambda x:'%.2f' % x

In [233]:
frame.applymap(format)

b      d      e
Utah     0.42   0.97   0.32
Ohio    -1.66  -0.16  -0.16
Texas   -0.31  -0.14  -1.37
Oregon  -0.53   1.09  -0.34

In [234]:
frame['e'].map(format)

Utah       0.32
Ohio      -0.16
Texas     -1.37
Oregon    -0.34
Name: e, dtype: object

In [235]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [237]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [238]:
obj.rank(method='min')

0    6.0
1    1.0
2    6.0
3    4.0
4    3.0
5    2.0
6    4.0
dtype: float64

In [240]:
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [245]:
obj = pd.Series(range(5),index=['a','a','c','d','d'])

In [246]:
obj

a    0
a    1
c    2
d    3
d    4
dtype: int64

In [248]:
obj.is_unique

True

In [249]:
obj.index.is_unique

False

In [254]:
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],
                  [np.nan,np.nan],[0.75,-1.3]],
                  index=['a','b','c','d'],
                  columns=['one','two'])

In [255]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [257]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [258]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [259]:
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [260]:
df.idxmax()

one    b
two    d
dtype: object

In [261]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [262]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [263]:
obj = pd.Series(['a','a','b','c'] *4)

In [264]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [266]:
obj.value_counts()

a    8
c    4
b    4
dtype: int64